version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:14
        auth:
          username: suhay
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Gatsby build
          command: yarn build
      - run:
          name: Zip up site
          command: |
            echo "Saving file ${CIRCLE_SHA1}.tar.gz"
            tar -zcvf ${CIRCLE_SHA1}.tar.gz public
      - store_artifacts:
          path: ${CIRCLE_SHA1}.tar.gz

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: SCP artifact
          command: scp ${CIRCLE_SHA1}.tar.gz ubuntu@suhay.dev:/mnt/projects/resume.suhay.dev/${CIRCLE_SHA1}.tar.gz

workflows:
  build_and_deploy:
    jobs:
      - build




      
