version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: 'cimg/node:14.14.0'
        auth:
          username: suhay
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Gatsby Build
          command: yarn build
      - run:
          name: Zip Up Site
          command: tar -zcvf "$CIRCLE_SHA1.tar.gz" public
      - store_artifacts:
          path: "$CIRCLE_SHA1.tar.gz"

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: SCP artifact
          command: scp ${CIRCLE_SHA1}.tar.gz ubuntu@suhay.dev:/mnt/projects/resume.suhay.dev/${CIRCLE_SHA1}.tar.gz

workflows:
  build_and_deploy:
    jobs:
      - build




      
